# NPM Plugin Release
name: npm-release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:
  publish:
    name: Check release to NPM
    runs-on: ubuntu-latest
    env:
      working-directory: ./plugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install Package 
        run: yarn install
        working-directory: ${{env.working-directory}}

      - name: Publish Package 
        run: npm publish --access public
        working-directory: ${{env.working-directory}}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
